### ISSUE TITLE
Hi from Ben

### ISSUE THREAD

**Issue by BenHutchisonSeek** [AlistairB/devbox#6]
You are a hard man to contact Alastair!

I realize I have no means of contacting you since leaving REA to Seek, as AFAICT you aren't on linkedin etc. https://alistairb.info/ doesnt seem to include any contact details, so I resorted to github ;)

Anyway, if you'd like to stay in touch, please email me from your email to my personal email brhutchison@gmail.com :)

**Comment by AlistairB** [comment]
Hi @BenHutchisonSeek, I emailed you :)
